# Generated by Django 4.2.6 on 2023-10-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_apps', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.BinaryField(),
        ),
    ]
